# docker-compose.yml (root)

version: "3.9"

services:
  # Node.js API + Static UI
  backend:
    container_name: employees-backend

    build:
      context: .
      dockerfile: apps/api-node/Dockerfile
      args:
        NODE_ENV: production

    # Map container’s 4000 → host’s 4700
    ports:
      - "4700:4000"

    # Environment variables connect to the *existing* Postgres container
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: employees-db          # name of the already‑running DB container
      DB_PORT: 5432
      DB_USER: emp_user
      DB_PASSWORD: StrongPassw0rd!
      DB_NAME: employees

    volumes:
      - ./apps/api-node/public:/usr/src/app/public:ro

    networks:
  employees-net:
    driver: bridge
