# docker-compose.yml (root)

services:
  # ───────────────────────────────────────────────────────────────
  #  Node.js API + Static UI
  # ───────────────────────────────────────────────────────────────
  backend:
    container_name: employees-backend

    build:
      context: ./apps/api-node
      dockerfile: Dockerfile
      args:
        NODE_ENV: production

    # Map container’s 4000 → host’s 4700
    ports:
      - "4700:4000"

    env_file:
      - ./apps/api-node/.env   # Make sure this file exists in CI

    volumes:
      - ./apps/api-node/public:/usr/src/app/public:ro

    depends_on:
      - db
    restart: unless-stopped

  # ───────────────────────────────────────────────────────────────
  #  PostgreSQL (Employees DB)
  # ───────────────────────────────────────────────────────────────
  db:
    image: postgres:15
    container_name: employees-db

    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: emp_user
      POSTGRES_PASSWORD: StrongPassw0rd!

    ports:
      - "5432:5432"

    volumes:
      - employees-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emp_user -d employees"]
      interval: 30s
      retries: 5

    restart: unless-stopped

volumes:
  employees-data:
