services:
  backend:
    build:
      context: .                        # monorepo root
      dockerfile: apps/api-node/Dockerfile
    container_name: employees-api
    environment:
      DATABASE_URL: postgresql://emp_user:StrongPassw0rd!@employees-db:5432/employees
      PORT: 4000
    ports:
      - "4000:4000"
    networks:
      - infra

networks:
  infra:
    external: true
