# /home/nishit/employees-app/docker-compose.yml

services:
  backend:
    build:
      context: .                        # monorepo root
      dockerfile: apps/api-node/Dockerfile
    container_name: employees-api
    environment:
      DATABASE_URL: postgresql://emp_user:StrongPassw0rd!@employees-db:5432/employees
      PORT: 4700
    ports:
      - "4700:4700"
    networks:
      - infra

networks:
  infra:
    external: true