version: "3.9"

services:
  backend:
    build: ./apps/api-node
    container_name: employees-api
    environment:
      DATABASE_URL: postgres://emp_user:StrongPassw0rd!@employees-db:5432/employees
      PORT: 4000
    ports:
      - "4000:4000"
    networks:
      - infra

networks:
  infra:
    external: true
