# docker-compose.yml (root)

services:
  # Node.js API + Static UI
  backend:
    container_name: employees-backend

    build:
      context: ./apps/api-node
      dockerfile: Dockerfile
      args:
        NODE_ENV: production

    # Map container's 4000 → host's 4700
    ports:
      - "4700:4000"

    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: employees-db      # external container name
      DB_PORT: 5432
      DB_USER: emp_user
      DB_PASSWORD: StrongPassw0rd!
      DB_NAME: employees

    volumes:
      - ./apps/api-node/public:/usr/src/app/public:ro

    networks:
      - employees-net

networks:
  employees-net:
    driver: bridge
