name: CI/CD on Self‑Hosted Runner

on:
  push:
    branches: [main]
  workflow_dispatch: {}

# Make sure only one deployment per branch happens at a time
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    # Simplified: match ANY self‑hosted runner in the repo/org
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # Node & npm cache speeds up subsequent runs
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/web/package-lock.json

      - name: Build React UI
        working-directory: apps/web
        shell: bash -euxo pipefail {0}
        run: |
          echo "::group::npm ci"
          npm ci
          echo "::endgroup::"

          echo "::group::npm run build"
          npm run build
          echo "::endgroup::"

      - name: Copy UI into backend
        shell: bash -euxo pipefail {0}
        run: |
          rm -rf apps/api-node/public
          mkdir -p apps/api-node/public
          cp -R apps/web/dist/* apps/api-node/public/

      - name: Tear down previous stack
        shell: bash -euxo pipefail {0}
        run: docker compose down --remove-orphans

      - name: Build & deploy Docker image
        shell: bash -euxo pipefail {0}
        run: |
          echo "::group::docker compose build"
          docker compose build --no-cache --progress=plain backend
          echo "::endgroup::"

          echo "::group::docker compose up"
          docker compose up -d
          echo "::endgroup::"
