name: CI/CD on Self‑Hosted Runner

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # Set up Node (no caching for now)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install all workspace/root dependencies so every package is present
      - name: Install root dependencies
        shell: bash -euxo pipefail {0}
        run: |
          echo "::group::npm install (root)"
          npm install
          echo "::endgroup::"

      - name: Build React UI
        working-directory: apps/web
        shell: bash -euxo pipefail {0}
        run: |
          echo "::group::npm run build"
          npm run build
          echo "::endgroup::"

      - name: Copy UI into backend
        shell: bash -euxo pipefail {0}
        run: |
          rm -rf apps/api-node/public
          mkdir -p apps/api-node/public
          cp -R apps/web/dist/* apps/api-node/public/

      - name: Tear down previous stack
        shell: bash -euxo pipefail {0}
        run: docker compose down --remove-orphans

      - name: Build & deploy Docker image
        shell: bash -euxo pipefail {0}
        run: |
          echo "::group::docker compose build"
          docker compose build --no-cache --progress=plain backend
          echo "::endgroup::"

          echo "::group::docker compose up"
          docker compose up -d
          echo "::endgroup::"
